### ISSUE TITLE
TypeError: currentReducer is not a function

### ISSUE THREAD

**Issue by dagenius007** [ankita1010/react-combine-reducers#2] opened 2020-03-06 06:05 UTC

**Comment by ankita1010** [comment] 2020-03-06 08:34
Hi @dagenius007 ,
Please provide some details of how you are trying to use the module (code snippets or sandbox will be excellent).
Thanks,
Ankita

**Comment by ankita1010** [comment] 2020-03-10 10:29
Closing the issue due to lack of information. Please reopen if the issue is encountered again.

**Closed by ankita1010** 2020-03-10 10:29 UTC
